/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lpoo.sistemaautescola.gui;

import classes.Administrativo;
import classes.Aluno;
import classes.Aula;
import classes.Curso;
import classes.Instrutor;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lpoo.sistemaautoescola.dao.PersistenciaJPA;

/**
 *
 * @author adrie
 */
public class CursoFrame extends javax.swing.JFrame {
    private Administrativo adm;
    private Curso c;
    private PersistenciaJPA jpa;
    /**
     * Creates new form CursoFrame
     */
    public CursoFrame() {
        initComponents();
        jpa = new PersistenciaJPA();
        carregaCursos();
        carregaCmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblCNHInstrutor = new javax.swing.JLabel();
        txtCNHInstrutor = new javax.swing.JTextField();
        lblInstrutor = new javax.swing.JLabel();
        lblCPFInstrutor = new javax.swing.JLabel();
        txtCPFInstrutor = new javax.swing.JTextField();
        lblNomeInstrutor = new javax.swing.JLabel();
        txtNomeInstrutor = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblRenach = new javax.swing.JLabel();
        lblCPFAluno = new javax.swing.JLabel();
        txtCPFAluno = new javax.swing.JTextField();
        txtRenach = new javax.swing.JTextField();
        lblAluno = new javax.swing.JLabel();
        lblNomeAluno = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        cmbFuncionario = new javax.swing.JComboBox<>();
        lblFuncionario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCursos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitulo.setText("Controle de Cursos");

        lblCNHInstrutor.setText("CNH:");

        txtCNHInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNHInstrutorActionPerformed(evt);
            }
        });
        txtCNHInstrutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCNHInstrutorKeyReleased(evt);
            }
        });

        lblInstrutor.setText("Busca por Instrutor:");

        lblCPFInstrutor.setText("CPF:");

        txtCPFInstrutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPFInstrutorKeyReleased(evt);
            }
        });

        lblNomeInstrutor.setText("Nome:");

        txtNomeInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeInstrutorActionPerformed(evt);
            }
        });
        txtNomeInstrutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeInstrutorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInstrutor)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblNomeInstrutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCNHInstrutor)
                        .addGap(18, 18, 18)
                        .addComponent(txtCNHInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCPFInstrutor)
                        .addGap(12, 12, 12)
                        .addComponent(txtCPFInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInstrutor)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeInstrutor)
                    .addComponent(txtNomeInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCNHInstrutor)
                    .addComponent(txtCNHInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCPFInstrutor)
                    .addComponent(txtCPFInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblRenach.setText("Renach:");

        lblCPFAluno.setText("CPF:");

        txtCPFAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPFAlunoKeyReleased(evt);
            }
        });

        txtRenach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRenachActionPerformed(evt);
            }
        });
        txtRenach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRenachKeyReleased(evt);
            }
        });

        lblAluno.setText("Busca por Aluno:");

        lblNomeAluno.setText("Nome:");

        txtNomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAlunoActionPerformed(evt);
            }
        });
        txtNomeAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeAlunoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAluno)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblNomeAluno)
                        .addGap(12, 12, 12)
                        .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblRenach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRenach, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(lblCPFAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAluno)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeAluno)
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRenach)
                    .addComponent(txtRenach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCPFAluno)
                        .addComponent(txtCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFuncionario.setText("Selecione o Funcionário:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(299, 299, 299))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFuncionario)
                            .addComponent(cmbFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
        );

        tblCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Aluno", "Instrutor", "Data Início", "Categoria", "Carga Horária", "Aulas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCursos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNovo)
                .addGap(18, 18, 18)
                .addComponent(btnRemover)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVisualizar)
                .addGap(191, 191, 191))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnVisualizar)
                    .addComponent(btnRemover))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        if((Administrativo)cmbFuncionario.getSelectedItem()!=null){
            CursoJDialog tela = new CursoJDialog(this, rootPaneCheckingEnabled);
            tela.setAdministrativo((Administrativo)cmbFuncionario.getSelectedItem());
            tela.setVisible(true);
            carregaCursos();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecionar funcionário administrativo antes de continuar.");
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if((Administrativo)cmbFuncionario.getSelectedItem()!=null){
            Curso curSel = getCursoSelecionado();
            if (curSel != null) {
                CursoJDialog tela = new CursoJDialog(this, rootPaneCheckingEnabled);
                tela.setCurso(curSel);
                tela.setVisible(true);
                carregaCursos();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecionar funcionário administrativo antes de continuar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        if((Administrativo)cmbFuncionario.getSelectedItem()!=null){
            Curso curSel = getCursoSelecionado();
            if (curSel != null) {
                if(curSel.getAluno() == null && curSel.getInstrutor() != null){
                    JOptionPane.showMessageDialog(rootPane, "Aviso: Aluno não existe mais/não foi selecionado na criação.");
                }
                if(curSel.getAluno() != null && curSel.getInstrutor() == null){
                    JOptionPane.showMessageDialog(rootPane, "Aviso: Instrutor não existe mais/não foi selecionado na criação.");
                }
                if(curSel.getAluno() == null && curSel.getInstrutor() == null){
                    JOptionPane.showMessageDialog(rootPane, "Aviso: Aluno e Instrutor não existem mais/não foram selecionados na criação.");
                }
                VisualizarFrame tela = new VisualizarFrame();
                tela.setCurso(curSel);
                tela.setVisible(true);
                
            }
            carregaCursos();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecionar funcionário administrativo antes de continuar.");
        }
        
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        Curso curSel = getCursoSelecionado();
        if (curSel != null) {
            int delOp = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja remover administrativo " + curSel + "?");
            if (delOp == JOptionPane.YES_OPTION) {
                    jpa.conexaoAberta();
                try {
                    jpa.remover(curSel);
                    JOptionPane.showMessageDialog(rootPane, "Veículo removido com sucesso!");
                    carregaCursos();
                } catch (Exception e) {
                    System.err.println("Erro ao remover veículo " + curSel + "\nErro: " + e.getMessage());
                } finally {
                    jpa.fecharConexao();
                }
            }
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void txtNomeInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeInstrutorActionPerformed

    private void txtNomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAlunoActionPerformed

    private void txtRenachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRenachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRenachActionPerformed

    private void txtCNHInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNHInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNHInstrutorActionPerformed

    private void txtNomeInstrutorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeInstrutorKeyReleased
        pesquisaCursos(txtNomeInstrutor.getText(), 3);
    }//GEN-LAST:event_txtNomeInstrutorKeyReleased

    private void txtCNHInstrutorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCNHInstrutorKeyReleased
        pesquisaCursos(txtCNHInstrutor.getText(), 4);
    }//GEN-LAST:event_txtCNHInstrutorKeyReleased

    private void txtCPFInstrutorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFInstrutorKeyReleased
        pesquisaCursos(txtCPFInstrutor.getText(), 5);
    }//GEN-LAST:event_txtCPFInstrutorKeyReleased

    private void txtNomeAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeAlunoKeyReleased
        pesquisaCursos(txtNomeAluno.getText(), 0);
    }//GEN-LAST:event_txtNomeAlunoKeyReleased

    private void txtRenachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRenachKeyReleased
        pesquisaCursos(txtRenach.getText(), 1);
    }//GEN-LAST:event_txtRenachKeyReleased

    private void txtCPFAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFAlunoKeyReleased
       pesquisaCursos(txtCPFAluno.getText(), 2);
    }//GEN-LAST:event_txtCPFAlunoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JComboBox<Administrativo> cmbFuncionario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JLabel lblCNHInstrutor;
    private javax.swing.JLabel lblCPFAluno;
    private javax.swing.JLabel lblCPFInstrutor;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblInstrutor;
    private javax.swing.JLabel lblNomeAluno;
    private javax.swing.JLabel lblNomeInstrutor;
    private javax.swing.JLabel lblRenach;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblCursos;
    private javax.swing.JTextField txtCNHInstrutor;
    private javax.swing.JTextField txtCPFAluno;
    private javax.swing.JTextField txtCPFInstrutor;
    private javax.swing.JTextField txtNomeAluno;
    private javax.swing.JTextField txtNomeInstrutor;
    private javax.swing.JTextField txtRenach;
    // End of variables declaration//GEN-END:variables

    private void carregaCursos() {
        jpa.conexaoAberta();
        List<Curso> listaCurso = jpa.getCursos();
        DefaultTableModel modeloTabela = (DefaultTableModel) tblCursos.getModel();
        modeloTabela.setRowCount(0);
        for (Curso curso : listaCurso) {
            Object aux1;
            Object aux2;
            if (curso.getAluno() != null) {
                aux1 = curso.getAluno().getNome();
            } else {
                aux1 = "Não existe";
            }
            if (curso.getInstrutor() != null) {
                aux2 = curso.getInstrutor().getNome();
            } else {
                aux2 = "Não existe";
            }
            Object[] linha = {
                curso,
                aux1,
                aux2,
                curso.getData_inicio(),
                curso.getCategoria(),
                curso.getCarga_horaria(),
                calculaAulas(curso),
             };
            modeloTabela.addRow(linha);
        }
        jpa.fecharConexao();
    }
    
    public void carregaCmb(){
        jpa.conexaoAberta();
        try{
            List<Administrativo> listaFunc = jpa.getAdministrativos();
            cmbFuncionario.removeAllItems();
            cmbFuncionario.addItem(null);
            for(Administrativo a : listaFunc){
                cmbFuncionario.addItem(a);
            }
        }catch(Exception e){
            System.out.println("Erro: "+e);
        }
        jpa.fecharConexao();
    }
    
        private Curso getCursoSelecionado() {
        int linhaSelecionada = tblCursos.getSelectedRow(); // Obtém a linha selecionada
        if (linhaSelecionada >= 0) { // Quando não tem nenhum objeto selecionado retorna -1
            DefaultTableModel modeloTabela = (DefaultTableModel) tblCursos.getModel();
            Curso cursoSelecionado = (Curso)modeloTabela.getValueAt(linhaSelecionada, 0); // A coluna 0 contém o objeto Veiculo
            return cursoSelecionado;
        } else {
            JOptionPane.showMessageDialog(this, "Nenhuma linha selecionada.");
            return null;
        }
    }
        
    public int calculaAulas(Curso c){
        return c.getAulas().size();
    }
    
    private void pesquisaCursos(String arg, int tipo){
        List<Curso> listaCursos = jpa.getCursos(arg, tipo);
        DefaultTableModel modeloTabela = (DefaultTableModel) tblCursos.getModel();
        modeloTabela.setRowCount(0);
        Object aux1;
        Object aux2;
        for (Curso curso : listaCursos) {
            if (curso.getAluno() != null) {
                aux1 = curso.getAluno().getNome();
            } else {
                aux1 = "Não existe";
            }
            if (curso.getInstrutor() != null) {
                aux2 = curso.getInstrutor().getNome();
            } else {
                aux2 = "Não existe";
            }
            Object[] linha = {
                curso,
                aux1,
                aux2,
                curso.getData_inicio(),
                curso.getCategoria(),
                curso.getCarga_horaria(),
                calculaAulas(curso)
            };
            modeloTabela.addRow(linha);
        }
    }
}
