/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package lpoo.sistemaautescola.gui;

import classes.Aula;
import classes.Curso;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import lpoo.sistemaautoescola.dao.PersistenciaJPA;

/**
 *
 * @author adrie
 */
public class VisualizarJDialog extends javax.swing.JDialog {
    private Curso curso;
    PersistenciaJPA jpa;
    
    public Curso getCurso(){
        return this.curso;
    }
    
    public void setCurso(Curso c){
        this.curso = c;
        String aux;
        if(curso.getAluno()!=null){
            aux = curso.getAluno().getNome();
            txtNomeAluno.setText(aux);
            aux = curso.getAluno().getCpf();
            txtCPFAluno.setText(aux);
            aux = curso.getData_inicio().toString();
            txtNascAluno.setText(aux);
            aux = curso.getAluno().getMatricula();
            txtMatriculaAluno.setText(aux);
            aux = curso.getAluno().getTelefone();
            txtTelefoneAluno.setText(aux);
            aux = curso.getAluno().getRenach();
            txtRenachAluno.setText(aux);
        }else{
            aux = null;
            txtNomeAluno.setText(aux);
            txtCPFAluno.setText(aux);
            txtNascAluno.setText(aux);
            txtMatriculaAluno.setText(aux);
            txtTelefoneAluno.setText(aux);
            txtRenachAluno.setText(aux);
        }
        if(curso.getInstrutor()!=null){
            aux = curso.getInstrutor().getNome();
            txtNomeInstrutor.setText(aux);
            aux = curso.getInstrutor().getCpf();
            txtCPFInstrutor.setText(aux);
            aux = curso.getInstrutor().getCnh();
            txtCNHInstrutor.setText(aux);
            aux = curso.getInstrutor().getData_de_nasc().toString();
            txtDataNascInstrutor.setText(aux);
            aux = curso.getInstrutor().getTelefone();
            txtTelefoneInstrutor.setText(aux);
        }else{
            aux = null;
            txtNomeInstrutor.setText(aux);
            txtCPFInstrutor.setText(aux);
            txtCNHInstrutor.setText(aux);
            txtDataNascInstrutor.setText(aux);
            txtTelefoneInstrutor.setText(aux);
        }
        if(curso.getAdministrativo()!=null){
            aux = curso.getInstrutor().getNome();
            txtNomeInstrutor.setText(aux);
            aux = curso.getInstrutor().getCpf();
            txtCPFInstrutor.setText(aux);
            aux = curso.getInstrutor().getCnh();
            txtCNHInstrutor.setText(aux);
            aux = curso.getInstrutor().getData_de_nasc().toString();
            txtDataNascInstrutor.setText(aux);
            aux = curso.getInstrutor().getTelefone();
            txtTelefoneInstrutor.setText(aux);
            aux = curso.getAdministrativo().getNome();
            txtNomeAdm.setText(aux);
            aux = curso.getAdministrativo().getCargo().toString();
            txtCargoAdm.setText(aux);
            aux = curso.getData_inicio().toString();
            txtDataInicio.setText(aux);
        }else{
            aux = null;
            txtNomeInstrutor.setText(aux);
            txtCPFInstrutor.setText(aux);
            txtCNHInstrutor.setText(aux);
            txtDataNascInstrutor.setText(aux);
            txtTelefoneInstrutor.setText(aux);
            txtNomeAdm.setText(aux);
            txtCargoAdm.setText(aux);
        }
        if(curso != null){
            aux = curso.getData_inicio().toString();
            txtDataInicio.setText(aux);
            carregaAulas(curso);
        }else{
            aux = null;
            txtDataInicio.setText(aux);
        }
    }
    /**
     * Creates new form VisualizarJDialog
     */
    public VisualizarJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jpa = new PersistenciaJPA();
    }

    
    private void carregaAulas(Curso c) {
        List<Aula> listaAulas = jpa.getAulas(c.getId());
        DefaultTableModel modeloTabela = (DefaultTableModel) tblAulas.getModel();
        modeloTabela.setRowCount(0);
        for (Aula a : listaAulas) {
            Object[] linha = {
                a,
                a.getDia_aula(),
                a.getConcluida(),
             };
            modeloTabela.addRow(linha);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeAluno = new javax.swing.JLabel();
        lblCPFAluno = new javax.swing.JLabel();
        txtCPFAluno = new javax.swing.JLabel();
        lblMatriculaAluno = new javax.swing.JLabel();
        txtMatriculaAluno = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        txtNascAluno = new javax.swing.JLabel();
        lblAluno = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JLabel();
        lblRenach = new javax.swing.JLabel();
        txtRenachAluno = new javax.swing.JLabel();
        lblTelefoneAluno = new javax.swing.JLabel();
        txtTelefoneAluno = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblAdministrativo = new javax.swing.JLabel();
        lblNomeAdm = new javax.swing.JLabel();
        txtNomeAdm = new javax.swing.JLabel();
        lblCargoAdm = new javax.swing.JLabel();
        txtCargoAdm = new javax.swing.JLabel();
        lblDataInicio = new javax.swing.JLabel();
        txtDataInicio = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblInstrutor = new javax.swing.JLabel();
        lbltxtNomeInstrutor = new javax.swing.JLabel();
        lblCPFInstrutor = new javax.swing.JLabel();
        lblCNHInstrutor = new javax.swing.JLabel();
        lblDataNascInstrutor = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtNomeInstrutor = new javax.swing.JLabel();
        txtCPFInstrutor = new javax.swing.JLabel();
        txtCNHInstrutor = new javax.swing.JLabel();
        txtDataNascInstrutor = new javax.swing.JLabel();
        txtTelefoneInstrutor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAulas = new javax.swing.JTable();
        btnAgenda = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNomeAluno.setText("Nome:");

        lblCPFAluno.setText("CPF:");

        txtCPFAluno.setText("Placeholder");

        lblMatriculaAluno.setText("Matrícula:");

        txtMatriculaAluno.setText("Placeholder");

        lblDataNasc.setText("Data de Nascimento:");

        txtNascAluno.setText("Placeholder");

        lblAluno.setText("Informações do Aluno:");

        txtNomeAluno.setText("Placeholder");

        lblRenach.setText("Renach:");

        txtRenachAluno.setText("jLabel11");

        lblTelefoneAluno.setText("Telefone:");

        txtTelefoneAluno.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMatriculaAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatriculaAluno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCPFAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPFAluno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomeAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeAluno))
                    .addComponent(lblAluno)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTelefoneAluno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefoneAluno)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDataNasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNascAluno))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRenach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRenachAluno)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeAluno)
                    .addComponent(txtNomeAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFAluno)
                    .addComponent(txtCPFAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatriculaAluno)
                    .addComponent(txtMatriculaAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoneAluno)
                    .addComponent(txtTelefoneAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRenach)
                    .addComponent(txtRenachAluno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNasc)
                    .addComponent(txtNascAluno))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        lblAdministrativo.setText("Informações administrativas:");

        lblNomeAdm.setText("Nome:");

        txtNomeAdm.setText("jLabel2");

        lblCargoAdm.setText("Cargo:");

        txtCargoAdm.setText("jLabel4");

        lblDataInicio.setText("Data de Início:");

        txtDataInicio.setText("jLabel6");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdministrativo)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNomeAdm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeAdm))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCargoAdm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCargoAdm))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblDataInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataInicio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdministrativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeAdm)
                    .addComponent(txtNomeAdm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargoAdm)
                    .addComponent(txtCargoAdm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataInicio)
                    .addComponent(txtDataInicio))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        lblInstrutor.setText("Informações do Instrutor:");

        lbltxtNomeInstrutor.setText("Nome:");

        lblCPFInstrutor.setText("CPF:");

        lblCNHInstrutor.setText("CNH:");

        lblDataNascInstrutor.setText("Data de Nascimento:");

        lblTelefone.setText("Telefone:");

        txtNomeInstrutor.setText("jLabel6");

        txtCPFInstrutor.setText("jLabel7");

        txtCNHInstrutor.setText("jLabel8");

        txtDataNascInstrutor.setText("jLabel9");

        txtTelefoneInstrutor.setText("jLabel10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCPFInstrutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPFInstrutor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDataNascInstrutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataNascInstrutor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbltxtNomeInstrutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeInstrutor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCNHInstrutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCNHInstrutor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefoneInstrutor))
                    .addComponent(lblInstrutor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInstrutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltxtNomeInstrutor)
                    .addComponent(txtNomeInstrutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFInstrutor)
                    .addComponent(txtCPFInstrutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCNHInstrutor)
                    .addComponent(txtCNHInstrutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefoneInstrutor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascInstrutor)
                    .addComponent(txtDataNascInstrutor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Data", "Concluída"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAulas);

        btnAgenda.setText("Agendar Nova Aula");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover Aula");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Informações sobre Curso de Direção");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnAgenda)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemover)
                        .addGap(18, 18, 18)
                        .addComponent(btnFechar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgenda)
                    .addComponent(btnFechar)
                    .addComponent(btnRemover))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisualizarJDialog dialog = new VisualizarJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdministrativo;
    private javax.swing.JLabel lblAluno;
    private javax.swing.JLabel lblCNHInstrutor;
    private javax.swing.JLabel lblCPFAluno;
    private javax.swing.JLabel lblCPFInstrutor;
    private javax.swing.JLabel lblCargoAdm;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblDataNascInstrutor;
    private javax.swing.JLabel lblInstrutor;
    private javax.swing.JLabel lblMatriculaAluno;
    private javax.swing.JLabel lblNomeAdm;
    private javax.swing.JLabel lblNomeAluno;
    private javax.swing.JLabel lblRenach;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTelefoneAluno;
    private javax.swing.JLabel lbltxtNomeInstrutor;
    private javax.swing.JTable tblAulas;
    private javax.swing.JLabel txtCNHInstrutor;
    private javax.swing.JLabel txtCPFAluno;
    private javax.swing.JLabel txtCPFInstrutor;
    private javax.swing.JLabel txtCargoAdm;
    private javax.swing.JLabel txtDataInicio;
    private javax.swing.JLabel txtDataNascInstrutor;
    private javax.swing.JLabel txtMatriculaAluno;
    private javax.swing.JLabel txtNascAluno;
    private javax.swing.JLabel txtNomeAdm;
    private javax.swing.JLabel txtNomeAluno;
    private javax.swing.JLabel txtNomeInstrutor;
    private javax.swing.JLabel txtRenachAluno;
    private javax.swing.JLabel txtTelefoneAluno;
    private javax.swing.JLabel txtTelefoneInstrutor;
    // End of variables declaration//GEN-END:variables
}
